name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Run linting
      run: |
        uv run black --check app models schemas tests *.py
        uv run ruff check app models schemas tests *.py
    
    - name: Run type checking
      run: |
        uv run mypy app models schemas
    
    - name: Run tests with coverage
      run: |
        uv run pytest -v --cov=app --cov=models --cov=schemas --cov-report=term-missing --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: backend
        name: backend-coverage